### ISSUE TITLE
Warface support.

### ISSUE THREAD

**Issue by nathan130200** [Markemp/Cryengine-Converter#140]
**Is your feature request related to a problem? Please describe.**
Its a feture request.

**Describe the solution you'd like**
Add support for Warface that uses DBA and CAF files.

**Additional context**
```cs
Version 829 of ChunkController is not supported

   at CgfConverter.CryEngineCore.Chunk.New[T](UInt32 version)
   at CgfConverter.CryEngineCore.Chunk.New(ChunkType chunkType, UInt32 version)
   at CgfConverter.CryEngineCore.Model.ReadChunks(BinaryReader reader)
   at CgfConverter.CryEngineCore.Model.Load(String fileName)
   at CgfConverter.CryEngine.ProcessCryengineFiles()
   at CgfConverterConsole.Program.Main(String[] args)
```
**Sample files for CAF and DBA**

[sample_files.zip](https://github.com/Markemp/Cryengine-Converter/files/9691477/sample_files.zip)

**Comment by nathan130200** [comment]
Thanks alot! Yeah, warface files uses some different methods to decrypt files, i will test and give feeback :D

**Comment by nathan130200** [comment]
I was able to test, i'm having an different exception now.

```cs
cgf-converter.exe "%cd%\combat_idleAimPoses_mech_01.caf" -objectdir "D:\WarfaceBackup\BR-1.18000.944.21500\Game_Ext"
Using up to 4 threads
Source [Filesystem]: D:\WarfaceBackup\BR-1.18000.944.21500\Game_Ext
Found input: D:\WarfaceBackup\br-1.18000.944.21500\game_ext\animations\boss\mech\combat\combat_idleaimposes_mech_01.caf
[INF:Program] [1/1 0.00%] D:\WarfaceBackup\br-1.18000.944.21500\game_ext\animations\boss\mech\combat\combat_idleaimposes_mech_01.caf
[INF:combat_idleaimposes_mech_01.caf] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[ERR:Program] Failed to render: D:\WarfaceBackup\br-1.18000.944.21500\game_ext\animations\boss\mech\combat\combat_idleaimposes_mech_01.caf
  AggregateException: One or more errors occurred. (Sequence contains no elements)
    InvalidOperationException: Sequence contains no elements
       at System.Linq.ThrowHelper.ThrowNoElementsException()
       at System.Linq.Enumerable.MinMaxInteger[T,TMinMax](IEnumerable`1 source)
       at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, IComparer`1 comparer)
       at CgfConverter.CryEngine.CreateMaterials()
       at CgfConverter.CryEngine.ProcessCryengineFiles()
       at CgfConverter.Program.ExportSingleModel(String inputFile)
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).
```

I really don't know how to convert these CAF/DBA files :(
