### ISSUE TITLE
Failure to read the ChunkBoneList on the newest Star Citizen files

### ISSUE THREAD

**Issue by lonelyhawk** [Markemp/Cryengine-Converter#156]
An attempt to convert the files like data\objects\spaceships\seats\anvl\carrack\anvl_carrack_command_station.cga results in the following exception:

```
Unhandled exception. System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
... << call stack here >>
   at System.IO.BinaryReader.PeekChar()
   at CgfConverter.CryEngineCore.ChunkBoneNameList_745.Read(BinaryReader b) in D:\...\CryEngineCore\Chunks\ChunkBoneNameList_745.cs:line 12
```

** Sample Model with the issue
- Star Citizen 3.18
- data\objects\spaceships\seats\anvl\carrack\anvl_carrack_command_station.cga

**Comment by LennartSolik** [comment]
Bump. Cant extrackt Objects/Spaceships - Program crashes when extracting Anvil files

**Comment by lonelyhawk** [comment]
> Bump. Cant extrackt Objects/Spaceships - Program crashes when extracting Anvil files

Can you provide a particular file you're having issues with? Anvil Carrack is the reason for the change and it's amazingly working now

**Comment by Markemp** [comment]
Just checked with the 3.21 SC files and the preliminary 1.6 version of the converter.  Looks like its working, at least with that version.

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/b5835457-d677-4735-85cb-ba060e79ccf7)

I'll close this when the 1.6 release is out if there aren't any other issues.

**Comment by Markemp** [comment]
Oh.  Looks a lot better when I turn on smooth shading.  Wasn't that the default back in the day?

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/bd4a759d-986d-44bd-bf71-c27ee9b2a186)

**Comment by Baconator650** [comment]
Could you quickly check 3.22 .cga files, ie the the new C1 ship model. I don't know if I compiled the latest 2.0 repo correctly, but .cga models were throwing an error.

**Comment by Markemp** [comment]
Missed this comment when it was originally posted.  Looks like the current 1.6 version can handle this though:
![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/cb20034c-dd8b-434b-8f91-457ff1441bf6)

Working on a draft 1.6 release and will have that posted soon.

**Comment by Markemp** [comment]
Cleaning up old issues.  This should be fixed.
