### ISSUE TITLE
3.23 Landing gear export is broken

### ISSUE THREAD

**Issue by N4me1es5** [Markemp/Cryengine-Converter#185]
**Describe the bug**
Since the Star Citizen Alpha 3.23 release the exporting of the ship using CGF Converter 1.6 is not working anymore. In 3.22.1 it still works

** Sample Model with the issue
- Game: Star Citizen
- Example Ship: Aegis Gladius

**Additional context**
Starfab 0.4.9 was used to export

**Comment by Baconator650** [comment]
Same issue with, attempted with Crusader C1 and Drake Corsair.

**Comment by N4me1es5** [comment]
After further testing it seems that Medguns and FPS weapons (all SKIN files) are broken

**Comment by Stormy151** [comment]
Can confirm extract of FPS weapons and gadgets SKIN files are broken for Star Citizen 3.23.  The medgun, for example- on extraction there are a bunch of errors for the SKIN files, and what you are left with to import appears to be a locator, a bunch of bones (armature) and a piece of geo that I believe is the piece the animated display/ammo count graphic is mapped to.  Not sure if any of this is helpful- I'm not a programmer. 

![2024-05-23 06_43_38-Blender](https://github.com/Markemp/Cryengine-Converter/assets/9356140/2b284a89-cdd0-49b9-9385-6472c5cd292d)

![2024-05-21 22_18_15-Window](https://github.com/Markemp/Cryengine-Converter/assets/9356140/babf93b7-7d7e-4f5f-b2c8-9326ad13f466)

**Comment by Baconator650** [comment]
I imagine the are cleaning up and redoing a lot of ids for server meshing.

**Comment by UsernameUnknowns** [comment]
is there any news about a fix yet for this bug?

**Comment by Markemp** [comment]
I'll be taking a look at it this weekend.

**Comment by Markemp** [comment]
Rant:  Learn to version your chunks, CIG.

**Comment by NeyMR** [comment]
issue is still active experiencing the same bug

```
RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\KRIG\P52_Merlin\landing_gear\KRIG_Merlin_Landing_Gear_Rear_Left_SKIN.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_left_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_left_skin.skin
[INF:krig_merlin_landing_gear_rear_left_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:krig_merlin_landing_gear_rear_left_skin.skin]    Objects/spaceships/ships/krig/p52_merlin/p52_Merlin
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_left_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Thrusters\KRIG\KRIG_Merlin_Thrusters\rsi_merlin_main_thruster.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\thrusters\krig\krig_merlin_thrusters\rsi_merlin_main_thruster.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\thrusters\krig\krig_merlin_thrusters\rsi_merlin_main_thruster.skin
[INF:rsi_merlin_main_thruster.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:rsi_merlin_main_thruster.skin]    objects/spaceships/ships/krig/p52_merlin/p52_Merlin
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\thrusters\krig\krig_merlin_thrusters\rsi_merlin_main_thruster.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\KRIG\P52_Merlin\landing_gear\KRIG_Merlin_Landing_Gear_Front_SKIN.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_front_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_front_skin.skin
[INF:krig_merlin_landing_gear_front_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:krig_merlin_landing_gear_front_skin.skin]    Objects/spaceships/ships/krig/p52_merlin/p52_Merlin
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_front_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\KRIG\P52_Merlin\landing_gear\KRIG_Merlin_Landing_Gear_Rear_Right_SKIN.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_right_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_right_skin.skin
[INF:krig_merlin_landing_gear_rear_right_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:krig_merlin_landing_gear_rear_right_skin.skin]    Objects/spaceships/ships/krig/p52_merlin/p52_Merlin
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\krig\p52_merlin\landing_gear\krig_merlin_landing_gear_rear_right_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\RSI\LandingGear\Constellation\LG_Rear4_Root_Skin.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear4_root_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear4_root_skin.skin
[INF:lg_rear4_root_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:lg_rear4_root_skin.skin]    Objects/Spaceships/Ships/RSI/Constellation/Constellation_Base/rsi_constellation_interior
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear4_root_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\RSI\LandingGear\Constellation\LG_Rear3_Root_Skin.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear3_root_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear3_root_skin.skin
[INF:lg_rear3_root_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:lg_rear3_root_skin.skin]    Objects/Spaceships/Ships/RSI/Constellation/Constellation_Base/rsi_constellation_interior
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear3_root_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\RSI\LandingGear\Constellation\LG_Rear2_Root_Skin.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear2_root_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear2_root_skin.skin
[INF:lg_rear2_root_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:lg_rear2_root_skin.skin]    Objects/Spaceships/Ships/RSI/Constellation/Constellation_Base/rsi_constellation_interior
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear2_root_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).



RSI_Constellation_Andromeda_Unmanned_NineTails: ERROR: model conversion failed for F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data\Objects\Spaceships\Ships\RSI\LandingGear\Constellation\LG_Rear1_Root_Skin.skin: 
Using up to 16 threads
Skipping texture output
Skipping nodes starting with any of these names: $physics_proxy
Skipping meshes using materials named: proxy, nocollision_faces
Source [Filesystem]: F:\StarFabExtract\RSI_Constellation_Andromeda\RSI_Constellation_Andromeda_Unmanned_NineTails\Data
No corresponding input file exist: -prefixmatnames
Found input: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear1_root_skin.skin
[INF:Program] [1/1 0.00%] F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear1_root_skin.skin
[INF:lg_rear1_root_skin.skin] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:lg_rear1_root_skin.skin]    Objects/Spaceships/Ships/RSI/Constellation/Constellation_Base/rsi_constellation_interior
[ERR:Program] Failed to render: F:\starfabextract\rsi_constellation_andromeda\rsi_constellation_andromeda_unmanned_ninetails\data\objects\spaceships\ships\rsi\landinggear\constellation\lg_rear1_root_skin.skin
  AggregateException: One or more errors occurred. (One or more errors occurred. (Index was outside the bounds of the array.))
    AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
      IndexOutOfRangeException: Index was outside the bounds of the array.
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model)
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject()
         at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render()
         at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers)
[INF:Program] Finished. Rendered 0 file(s)
[ERR:Program] Failed to convert 1 file(s).
```

**Comment by Markemp** [comment]
I just tested the 1.6.1 code against the Krig and Connie landing gears, and it looks like it was working:

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/3073fa22-205d-4e2b-9fca-6d05d344a510)

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/d85d9a92-a792-42ea-9fdd-898c71ba607c)

I'll keep digging around to see if I'm missing something else though.

**Comment by NeyMR** [comment]
so it will be working in 1.6.1?

**Comment by NeyMR** [comment]
> so it will be working in 1.6.1?

Ok was my bad on my last message, rebuilt solution and all went well no issues or errors..

**Comment by NeyMR** [comment]
Ok I found a small issue the wings of the Merling not showing or extracted with model

![image](https://github.com/Markemp/Cryengine-Converter/assets/79515649/568b4cef-854a-4873-ab9f-781716959b1b)

**Comment by Markemp** [comment]
It looks like the left and right wings are separate models:

KRIG_P52_Merlin_Wing_Right.cga
KRIG_P52_Merlin_Wing_Left.cga

**Comment by NeyMR** [comment]
> It looks like the left and right wings are separate models:
> 
> KRIG_P52_Merlin_Wing_Right.cga KRIG_P52_Merlin_Wing_Left.cga

How would I go into including them in export?

**Comment by Markemp** [comment]
I'm not really sure.  I think that's a Starfab thing?  I just individually extracted them and imported them separately into Blender:

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/b44d8808-9dd3-48bd-bbed-e41779b6cc3e)

**Comment by NeyMR** [comment]
> I'm not really sure. I think that's a Starfab thing? I just individually extracted them and imported them separately into Blender:
> 
> ![image](https://private-user-images.githubusercontent.com/12057128/339175983-b44d8808-9dd3-48bd-bbed-e41779b6cc3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDIwNjAsIm5iZiI6MTcxODI0MTc2MCwicGF0aCI6Ii8xMjA1NzEyOC8zMzkxNzU5ODMtYjQ0ZDg4MDgtOWRkMy00OGJkLWJiZWQtZTQxNzc5YjZjYzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxMjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTUzN2EwY2E5ZTA3MzJmNzMzN2I4NjgxMWI4NjNiNjIyNDE4ODIyZjQxNTRmODgzYWMyNzJlYzM3NzY3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ZMeHGVlP7C1BCrbaBzXQoXJysbeW1iZ82Jy-N4QuN8)

Searched for 
KRIG_P52_Merlin_Wing_Right.cga
KRIG_P52_Merlin_Wing_Left.cga

search result no return, can you help me find it?

**Comment by Markemp** [comment]
I'm not really sure.  I think that's a Starfab thing?  I just individually extracted them and imported them separately into Blender:

![image](https://github.com/Markemp/Cryengine-Converter/assets/12057128/b44d8808-9dd3-48bd-bbed-e41779b6cc3e)

**Comment by Markemp** [comment]
I'm not sure how Starfab works.  You'll have to ask the authors of that program how to build the ship.

**Comment by NeyMR** [comment]
> I'm not sure how Starfab works. You'll have to ask the authors of that program how to build the ship.

can you send me the wings in a blend file please?

**Comment by Baconator650** [comment]
> > I'm not sure how Starfab works. You'll have to ask the authors of that program how to build the ship.
> 
> can you send me the wings in a blend file please?

If you need help with StarFab, I suggest you join the discord [(https://gitlab.com/scmodding/scmodding)](url) where there individuals who can help you and video tutorials such as 

[https://www.youtube.com/watch?v=5unXj1Pnuis&t=8s](url)

[https://www.youtube.com/playlist?list=PLr5XU4B6R4l7foInuEgICpKm6BnuxQZyF](url)

Also please familiarize yourself with the legal **TOS** with Star Citizen. In short, the sharing of asset files are not legal (such as entire ships or parts of ships), but CiG does allow the extraction of assets for personal projects without any prior agreements..

**Comment by NeyMR** [comment]
thank you!


> > > I'm not sure how Starfab works. You'll have to ask the authors of that program how to build the ship.
> > 
> > 
> > can you send me the wings in a blend file please?
> 
> If you need help with StarFab, I suggest you join the discord [(https://gitlab.com/scmodding/scmodding)](url) where there are individuals who can help you and video tutorials such as
> 
> [https://www.youtube.com/watch?v=5unXj1Pnuis&t=8s](url)
> 
> [https://www.youtube.com/playlist?list=PLr5XU4B6R4l7foInuEgICpKm6BnuxQZyF](url)
> 
> Also please familiarize yourself with the legal **TOS** with Star Citizen. In short, the sharing of asset files are not legal (such as entire ships or parts of ships), but CiG does allow the extraction of assets for personal projects without any prior agreements..

**Comment by Baconator650** [comment]
It looks like the Anvil Hornet MKII Main thruster nozzle and P72 Nozzle (.skin) is not converting.

**Comment by Markemp** [comment]
Looks like these are working in 1.7.0, although the performance was bad.  

![Image](https://github.com/user-attachments/assets/78bcf284-7d70-4c1c-b41d-ae7a5edc68c3)
