### ISSUE TITLE
EPTU 4.0 Models Are Not Converting Correctly

### ISSUE THREAD

**Issue by kinshadow** [Markemp/Cryengine-Converter#194]
I've tried to convert a good number of files from the new SC EPTU 4.0 release and they all see to be bad output.  From manual inspection of some of the converted output files, they seem to have face indices, but are missing vertex data. 

On the files that give output, there are no explicit errors in the 1.6.1 released version.  I tried building a debug version off the main branch and got the following:

```
PS C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\bin\Debug\net8.0\win-x64> .\cgf-converter.exe .\m_ksar_heavy_armor_helmet_01_prop.cgf
Using up to 24 threads
Found input: C:\users\brian\downloads\cryengine-converter-master (7)\cryengine-converter-master\cgf-converter\bin\debug\net8.0\win-x64\m_ksar_heavy_armor_helmet_01_prop.cgf
[INF:Program] [1/1 0.00%] C:\users\brian\downloads\cryengine-converter-master (7)\cryengine-converter-master\cgf-converter\bin\debug\net8.0\win-x64\m_ksar_heavy_armor_helmet_01_prop.cgf
[INF:m_ksar_heavy_armor_helmet_01_prop.cgf] Found following potential material files.  If you are not specifying a material file and the materials don't look right, trying one of the following files:
[INF:m_ksar_heavy_armor_helmet_01_prop.cgf]    m_ksar_heavy_armor_helmet_01_01_01
Unhandled exception. System.AggregateException: One or more errors occurred. (The given key '5' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '5' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteGeometries(Model model) in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\CgfConverter\Renderers\Collada\ColladaModelRenderer.cs:line 568
   at CgfConverter.Renderers.Collada.ColladaModelRenderer.WriteLibrary_Geometries() in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\CgfConverter\Renderers\Collada\ColladaModelRenderer.cs:line 509
   at CgfConverter.Renderers.Collada.ColladaModelRenderer.GenerateDaeObject() in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\CgfConverter\Renderers\Collada\ColladaModelRenderer.cs:line 97
   at CgfConverter.Renderers.Collada.ColladaModelRenderer.Render() in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\CgfConverter\Renderers\Collada\ColladaModelRenderer.cs:line 65
   at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers) in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\cgf-converter.cs:line 152
   --- End of inner exception stack trace ---
   at CgfConverter.Program.RunRenderersAndThrowAggregateExceptionIfAny(IEnumerable`1 renderers) in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\cgf-converter.cs:line 161
   at CgfConverter.Program.ExportSingleModel(String inputFile) in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\cgf-converter.cs:line 131
   at CgfConverter.Program.Run() in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\cgf-converter.cs:line 62
   at CgfConverter.Program.Main(String[] args) in C:\Users\brian\Downloads\Cryengine-Converter-master (7)\Cryengine-Converter-master\cgf-converter\cgf-converter.cs:line 45



```

**Comment by Markemp** [comment]
All `.cga`\`.cgf` files right now are going to be broken, as those were converted over to Ivo format as of 3.24.  The other issue is tracking those changes and hopefully will be solved by the end of the year.  Hopefully 4.0 will provide stability with the models, as the 3.24 changes deal with the last of the remaining classic Lumberyard files.  

I'm going to hold off on looking at this until 4.0 comes out, since I'm hoping the 3.24 updates will solve them all. 🤞

**Comment by kinshadow** [comment]
OK, gotcha.  Fingers crossed the Ivo fix will apply here as well.  Note, while the error example I copied was cgf, but all the file formats I tried had the same bad output issue.

**Comment by Sergentval** [comment]
> All `.cga``.cgf` files right now are going to be broken, as those were converted over to Ivo format as of 3.24. The other issue is tracking those changes and hopefully will be solved by the end of the year. Hopefully 4.0 will provide stability with the models, as the 3.24 changes deal with the last of the remaining classic Lumberyard files.
> 
> I'm going to hold off on looking at this until 4.0 comes out, since I'm hoping the 3.24 updates will solve them all. 🤞

did you have any idea or anything we can do for helping you out ?

**Comment by Markemp** [comment]
The other issue is tracking the Ivo updates.  Got most of the work done, but I still need to sort out transforms.  Once those are done I'll get a 1.7 release out, then work on the 4.0 updates.

It's just taking time.  :(

**Comment by Sergentval** [comment]
> The other issue is tracking the Ivo updates.  Got most of the work done, but I still need to sort out transforms.  Once those are done I'll get a 1.7 release out, then work on the 4.0 updates.
> 
> It's just taking time.  :(

Thx for your work ! I will waiting to try out 👀

**Comment by Markemp** [comment]
![Image](https://github.com/user-attachments/assets/945910d7-0fa9-4d20-996c-97b6b575fd2c)

The current test build seems to work with this.

**Comment by Markemp** [comment]
Fixed in v1.7.0.
