### ISSUE TITLE
Error on conversion to DAE with some SC assets

### ISSUE THREAD

**Issue by vmxeo** [Markemp/Cryengine-Converter#33]
Running release 1.05 on SC files, I'm intermittently getting the following error during conversion to DAE:

```
********************************************************************************
There was an error rendering X:\sc38\Data\Objects\Spaceships\ships\AEGS\Reclaimer\Exterior\AEGS_Reclaimer.cga

Object reference not set to an instance of an object.

   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 0
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1200
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateSimpleNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1236
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1162
   at CgfConverter.COLLADA.WriteLibrary_VisualScenes() in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1058
   at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 23
   at CgfConverterConsole.Program.Main(String[] args)
********************************************************************************
```

This isn't happening on all files; files with this error are not converted.

**Comment by shayne44** [comment]
I'm seeing it all over the place too. Older versions _may_ have converted these but DAE wasn't working correctly then. 

[ORIG_600i.zip](https://github.com/Markemp/Cryengine-Converter/files/4527291/ORIG_600i.zip)

Attached for convenience.
```
********************************************************************************
There was an error rendering .\Data\Objects\Spaceships\Ships\ORIG\600i\Exterior\ORIG_600i.cga

Object reference not set to an instance of an object.

   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 0
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1200
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1200
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1200
   at CgfConverter.COLLADA.CreateChildNodes(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1253
   at CgfConverter.COLLADA.CreateSimpleNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1236
   at CgfConverter.COLLADA.CreateNode(ChunkNode nodeChunk) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1162
   at CgfConverter.COLLADA.WriteLibrary_VisualScenes() in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 1058
   at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 23
   at CgfConverterConsole.Program.Main(String[] args)
********************************************************************************
```

**Comment by Markemp** [comment]
I think I have this fixed now.  The issue was due to the geometry file not having a node that matched the name in the node file.  I'm going to work on getting colors added, then make a new release with both features.  But you can build from the latest commit and it should be able to handle these files now.

**Comment by Markemp** [comment]
![image](https://user-images.githubusercontent.com/12057128/80867733-9bf1b900-8c4a-11ea-8720-5b841a2adbd4.png)

Nice.
