### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by Dexin-Ruyitang** [Markemp/Cryengine-Converter#34]
Some Cryengine skin files have problems

**************
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CgfConverter.COLLADA.WriteLibrary_Geometries() in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 389
   at CgfConverter.COLLADA.GenerateDaeObject() in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 56
   at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 23
   at CgfConverterConsole.Program.Main(String[] args)
**************
It doesn't come out the dae file. How to solve it?

**Comment by Markemp** [comment]
Which game is this for?  I need a bit more info to be able to work on this.

**Comment by Markemp** [comment]
Closing.  Will reopen if there is more info.
