### ISSUE TITLE
Render Error .skin Unsupported FileSignature #ivo

### ISSUE THREAD

**Issue by MrTeaRexx** [Markemp/Cryengine-Converter#36]
Unsupported FileSignature #ivo

at CgfConverter.CryEngineCore.Model.Read_FileHeader(BinaryReader b) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:line 198
at CgfConverter.CryEngineCore.Model.Load(String fileName) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:line 163
at CgfConverter.CryEngine..ctor(String fileName, String dataDir) in C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine\CryEngine.cs:line 108
at CgfConverterConsole.Program.Main(String[] args)

helping a friend make a ravager Gel Blaster from Star Citizen and it can't read the files

**Comment by TheMightyPilot** [comment]
Hey, I'm also having the same issue attempting to extract the Atzkav sniper from Star Citizen 3.11.0
I got this error when it came to extracting .skin files for the weapon, for example: esnp_fps_lbco_atzkav_parts.skin

Just wondering if there is any update available just now if this looks like it is fixable?

**Comment by Markemp** [comment]
It should be fixable, but will have to wait a bit longer.  Finishing up grad school soon, and will have a lot more time to work on this in March.  Sorry for the delay. :(

**Comment by Markemp** [comment]
I'm going to close this issue as it's the same one as Issue #42, even though this one was filed first.  I'm working on converting the new #ivo skin files and hope to have something ready this weekend.  If you have further updates, please post them in that thread.  Thank you again for your help with this!
