### ISSUE TITLE
ArcheAge files:  Fix armature rotations

### ISSUE THREAD

**Issue by Markemp** [Markemp/Cryengine-Converter#48]
Probably uses Quaternions like Sonic Boom.

**Comment by sunkhaskasis** [comment]
Does this issue have anything to do with the fact that it only imports a mesh with a single (root) bone? Just wondering. Here's an example with the `coupleduckship_foot.chr` model from the closed issue of mine.
![image](https://user-images.githubusercontent.com/19194315/116928296-8f40e000-ac65-11eb-9846-4f8949ec9e90.png)

**Comment by Markemp** [comment]
No, I think it's using a different rotation system.  Should be a pretty easy fix if I can ever find the time for it.

**Comment by sunkhaskasis** [comment]
Don't know if this is related to that issue, but this is the error I get when I try using the Cryengine Importer on the converted .dae:
```Python: Traceback (most recent call last):
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\__init__.py", line 110, in execute
    return Cryengine_Importer.import_asset(context, **keywords)
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 509, in import_asset
    constants.basedir = get_base_dir(path)
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  [Previous line repeated 991 more times]
  File "C:\Users\<redacted>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 48, in get_base_dir
    if os.path.basename(dirpath).lower() == 'objects' or os.path.basename(dirpath).lower() == 'prefabs':
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 184, in split
    seps = _get_bothseps(p)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

location: <unknown location>:-1
```

**Comment by sunkhaskasis** [comment]
I apologize if I'm getting you off your track with this since you appear to be occupied with the SC models right now, but it appears that the converter doesn't work with the `porpoise` model sample from the issue #20 . It reads "Version 801 of ChunkCompiledPhysicalProxies is not supported". Just to let you know. Carry on with your work.

**Comment by sunkhaskasis** [comment]
Just FYI, it appears that the latest release has messed up some things in AA models. One of the affected strings is `Controller-joints` in the converted duck ship feet .dae file:

```          <Name_array id="Controller-joints-array" count="23">Bip01 ����      oint04 S&#x12;�=��&#x1F;�޻~?��&#x13;?�rs��&#xE;�&gt;_T�=�&#x16;y�?J���t�+�)�v�&#x5;?&#x16;      l_03 �&amp;^s����&gt;&#x7;&gt;ʽ�&#x11;y��͗��yt���#&lt;��&#x5;?&#x1E;</Name_array>```

**Comment by Markemp** [comment]
One of the weird issues with these models is that there doesn't seem to be the transform matrix information for the bones.  I can get the geometry to rotate for the bones, but the bones just aren't in the right place.  Not sure on how to fix this issue, but will investigate as time permits.  At least the geometry works, and the bones... "work". :(

**Comment by Markemp** [comment]
Fix planned for v2.0
