### ISSUE TITLE
ArcheAge "Version 801 of ChunkCompiledPhysicalProxies is not supported"

### ISSUE THREAD

**Issue by 0x795E69D8** [Markemp/Cryengine-Converter#74]
Some of the models seem to use a version 801 of ChunkCompiledPhysicalProxies which isn't supported yet.
I found this to be the case on some of the base character models. Full error message is
```
********************************************************************************
There was an error rendering dw_m_base.chr

Version 801 of ChunkCompiledPhysicalProxies is not supported

   at CgfConverter.CryEngineCore.Chunk.New[T](UInt32 version) in CgfConverter\CryEngineCore\Chunks\Chunk.cs:line 145
   at CgfConverter.CryEngineCore.Chunk.New(ChunkType chunkType, UInt32 version) in CgfConverter\CryEngineCore\Chunks\Chunk.cs:line 62
   at CgfConverter.CryEngineCore.Model.ReadChunks(BinaryReader reader) in CgfConverter\CryEngineCore\Model.cs:line 190
   at CgfConverter.CryEngineCore.Model.Load(String fileName) in CgfConverter\CryEngineCore\Model.cs:line 115
   at CgfConverter.CryEngine.ProcessCryengineFiles() in CgfConverter\CryEngine\CryEngine.cs:line 103
   at CgfConverterConsole.Program.Main(String[] args) in cgf-converter\cgf-converter.cs:line 67
********************************************************************************
```
If needed I can also supply model files to replicate that.

**Comment by sunkhaskasis** [comment]
I believe it's a known issue since I've already provided a sample which outputs this exact error. Refer to the issue #20 .

**Comment by Kukami** [comment]
The issue you mentioned seems to be about version 801 of ChunkCompiledBones for which support was added a while ago. What I'm having problems is Version 801 of ChunkCompiledPhysicalProxies which seems to be a different thing unless I have missed something here

**Comment by sunkhaskasis** [comment]
Right, it looks like I forgot to elaborate. I mentioned it in another issue related to AA: #48

**Comment by Kukami** [comment]
Ah yeah I did not see that before, I'm sorry for the duplicate then

**Comment by Markemp** [comment]
@Kukami Actually I don't have any models with the 801 version of CompiledPhysicalProxies.  Any idea where I can find one like the one from the initial post?

**Comment by QLVermeire** [comment]
Hello @Markemp has there been any news on this? I'm aware it's a two year old issue but I thought I would check in and ask.

**Comment by BrisketJJAMPPONG** [comment]
hello @Markemp , I'm still having the same problem.
It seems that the problem is caused by the recently created .chr file.
Please let me know if there is any way to solve it.
********************************************************************************
There was an error rendering F:\archeageunpack\version2\game\objects\characters\dwarf\male\costume\dw_m_sk_flowerbunny001\dw_m_sk_flowerbunny001.chr

Version 801 of ChunkCompiledPhysicalProxies is not supported

   at CgfConverter.CryEngineCore.Chunk.New[T](UInt32 version)
   at CgfConverter.CryEngineCore.Chunk.New(ChunkType chunkType, UInt32 version)
   at CgfConverter.CryEngineCore.Model.ReadChunks(BinaryReader reader)
   at CgfConverter.CryEngineCore.Model.Load(String fileName)
   at CgfConverter.CryEngine.ProcessCryengineFiles()
   at CgfConverterConsole.Program.Main(String[] args)
********************************************************************************
[dw_m_sk_flowerbunny001.zip](https://github.com/Markemp/Cryengine-Converter/files/11302623/dw_m_sk_flowerbunny001.zip)

**Comment by Markemp** [comment]
This should be fixed with the v1.6 release.

**Comment by Markemp** [comment]
Aside from the jacked up armature (known issue, tracked in other issues), these models will now import.  Closing this and will continue to investigate the armature problems.

![Image](https://github.com/user-attachments/assets/70fabdd7-e834-429d-935d-49a79ddb6ef0)
